### ISSUE TITLE
Using single header outcome-basic breaks clang compilation with placement deallocation functions

### ISSUE THREAD

**Issue by apmanol** [ned14/quickcpplib#47] opened 2023-07-14 12:26 UTC
Hello,

something very strange, with `clang++` using the [outcome-basic](https://github.com/ned14/outcome/blob/develop/single-header/outcome-basic.hpp)

```
clang++ --version 
clang version 15.0.7 (Fedora 15.0.7-2.fc37)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```cpp

#include "outcome-basic.hpp"

// A std::unique_ptr deleter that deletes memory allocated via ::operator new.
#if defined(__cpp_sized_deallocation)
class TrivialDeleter {
 public:
  explicit TrivialDeleter(std::size_t size) : size_(size) {}

  void operator()(void* target) const {
    ::operator delete(target, size_);
  }

 private:
  std::size_t size_;
};
#else   // __cpp_sized_deallocation
class TrivialDeleter {
 public:
  explicit TrivialDeleter(std::size_t) {}

  void operator()(void* target) const { ::operator delete(target); }
};
#endif  // __cpp_sized_deallocation
int main()
{
  TrivialDeleter deleter(4u);
  return 0;
}
```

with error:

```
lang++  -std=c++17 ll.cc -I/projects/icom/babel/thirdparty/abseil-cpp/ 
ll.cc:16:5: error: no matching function for call to 'operator delete'
    ::operator delete(target, size_);
    ^~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/new:144:6: note: candidate function not viable: no known conversion from 'const std::size_t' (aka 'const unsigned long') to 'const std::nothrow_t' for 2nd argument
void operator delete(void*, const std::nothrow_t&) _GLIBCXX_USE_NOEXCEPT
     ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/new:153:6: note: candidate function not viable: no known conversion from 'const std::size_t' (aka 'const unsigned long') to 'std::align_val_t' for 2nd argument
void operator delete(void*, std::align_val_t)
     ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/new:180:13: note: candidate function not viable: no known conversion from 'const std::size_t' (aka 'const unsigned long') to 'void *' for 2nd argument
inline void operator delete  (void*, void*) _GLIBCXX_USE_NOEXCEPT { }
            ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/new:130:6: note: candidate function not viable: requires 1 argument, but 2 were provided
void operator delete(void*) _GLIBCXX_USE_NOEXCEPT
     ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/new:155:6: note: candidate function not viable: requires 3 arguments, but 2 were provided
```

In  [godbolt](https://godbolt.org/z/bY1Mcovx8) the error appears in clang <16

**Comment by ned14** [comment] 2023-07-14 18:27
Why transfer to quickcpplib? This is surely an Outcome problem?

**Comment by BurningEnlightenment** [comment] 2023-07-14 18:28
So, there are multiple issues overshadowing each other here:

First of all, your feature check is broken, the compiler is allowed to define `__cpp_sized_deallocation` to `0` for older standards:
```diff
-#if defined(__cpp_sized_deallocation)
+#if __cpp_sized_deallocation >= 201309L
```

Then there is the fact that quickcpplib (included with outcome) does the following:
https://github.com/ned14/quickcpplib/blob/59105c65f6c86103ce26c0aac5716a106e758163/include/quickcpplib/cpp_feature.h#L208-L210

And finally [sized (de-)allocation support is disabled in clang by default](https://reviews.llvm.org/D112921). You must explicitly enable it with `-fsized-deallocation`.

**Comment by BurningEnlightenment** [comment] 2023-07-14 18:33
One could argue that quickcpplib shouldn't touch the feature macros, but otherwise I think this can be closed as invalid/wontfix/working as intended.

Anyways, thank you for the BR!

**Comment by ned14** [comment] 2023-07-14 18:37
Ah, but look at https://godbolt.org/z/b3P33qYzW! The OP has revealed a bug!

I got started on a fix here, but I'll need to wait until work is finished before I can look into it properly, because it didn't "just work".

**Comment by BurningEnlightenment** [comment] 2023-07-14 18:48
Probably due to a reduction of transitively included headers in libstdc++. 

I observed another compile failure on my machine when I started testing with the following reprex and `libstdc++12`:
```cpp
#include <outcome/basic_outcome.hpp>

int main()
{
}
```
```
λ  clang++ -std=c++14 -I/home/me/ldevel/vcpkg/installed/x64-linux/include compile-test.cpp
In file included from compile-test.cpp:2:
In file included from /home/me/ldevel/vcpkg/installed/x64-linux/include/outcome/basic_outcome.hpp:32:
/home/me/ldevel/vcpkg/installed/x64-linux/include/outcome/detail/basic_outcome_failure_observers.hpp:54:89: error: no type named 'exception_ptr' in namespace 'std'
  template <class exception_type> inline exception_type current_exception_or_fatal(std::exception_ptr e) { std::rethrow_exception(e); }
[…]
λ  clang++ --version
Ubuntu clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
But these are strictly different issues.

**Comment by BurningEnlightenment** [comment] 2023-07-15 05:40
I'm going ahead and close this as it is working as intended. However, if you feel that quickcpplib shouldn't define the feature test macros based on the `__cplusplus` value, you may open an enhancement issue here. 

Thanks again for the BR!

**Closed by BurningEnlightenment** 2023-07-15 05:40 UTC
Labels: invalid

**Comment by apmanol** [comment] 2023-07-15 06:03
Thank you all for the help and the snap replies!

**Comment by BurningEnlightenment** [comment] 2023-07-16 08:10
@ned14 do you happen to know someone involved with cppreference? Their [C++14 compiler compatibility table](https://en.cppreference.com/w/cpp/compiler_support/14) incorrectly marks sized deallocations as supported instead of maybe supported on Clang. And while I [nudged them on the discussion page](https://en.cppreference.com/w/Talk:cpp/compiler_support), I'm uncertain whether people with edit-power actually follow that page 😅

**Comment by ned14** [comment] 2023-07-16 11:54
Wikis are generally go ahead and fix things yourself, if others don't like your changes they'll revert them.

**Comment by BurningEnlightenment** [comment] 2023-07-16 12:39
Yes, but specifically the compatibility table templates are edit-restricted and I'm not on the whitelist 😞
